### ISSUE TITLE
Too much padding

### ISSUE THREAD

**Issue by thany** [NicoNekoru/obsidan-advanced-table-xt#10] opened 2023-09-14 08:37 UTC
It's in your own examples too. Without this plugin, tables have normal/minimal padding, as they should have.

Once this plugin is installes and enabled, every table that gets touched (and only then, for some reason) gets a huge amount of cell padding.

Why is that? And can it be fixed please?

**Comment by NicoNekoru** [comment] 2023-09-14 16:17
Dupe of #8

**Closed by NicoNekoru** 2023-09-14 16:17 UTC
